services:
  frontend:
    image: ghcr.io/harutokitagawa/ifeel/frontend:0.1.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    image: ghcr.io/harutokitagawa/ifeel/backend:0.1.0
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - emotion_analysis
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - EMOTION_API=http://emotion_analysis:5000

  emotion_analysis:
    image: ghcr.io/harutokitagawa/ifeel/emotion_analysis:0.1.0
    ports:
      - "5001:5000"
    volumes:
      - ./emotion_analysis:/app
    env_file:
      - emotion_analysis/.env

  neo4j:
    image: neo4j:5.26
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password